// ELLE DERLENDİ — tymm.meb.gov.tr sayfalarından web_fetch ile çekilip
// düzeyi (kod+ad+tanım, en fazla 2 seviye) scripts/scrape-skills.mjs ile
// aynı ilkeyle derlendi: 3. seviye "süreç bileşenleri/göstergeler" alınmadı.
// Derleme tarihi: 2026-08-05 | Kaynak: https://tymm.meb.gov.tr/beceriler/*
//
// KAPSAM DIŞI (bilinen eksikler):
//   - Fiziksel Beceriler: kaynak sayfada ayrı bir kod/ad listesi yok
//     (yalnızca kavramsal anlatım) — scrape-skills.mjs de burada boş
//     sonuç dönderirdi.
//   - Alan Becerileri: tek sayfa değil, her ders ailesi için ayrı bir
//     sayfa (ör. BEOSAB: Beden Eğitimi/Oyun/Spor, BTYAB: Bilişim
//     Teknolojileri ve Yazılım). Ayrı bir kazı gerektirir, bu dosyaya
//     dahil edilmedi.
//   - İngilizce ve dil dersleri: TYMM sitesinde CEFR tabanlı farklı bir
//     yapı kullanıyor, bu kategorilerin kapsamına girmiyor.

export interface Beceri {
  kod: string // örn. "KB2.1", "SDB1.3", "E1.1", "D3", "OB4.2"
  ad: string
  tanim?: string // kaynak sayfada tanım cümlesi varsa; yoksa boş bırakıldı
}

export const SKILLS: Record<string, Beceri[]> = {
  "Erdem-Değer-Eylem Çerçevesi": [
    { kod: "D1", ad: "Adalet", tanim: "Hak ve özgürlükleri, eşitliği, etik davranmayı, hakkaniyeti, ön yargısızlığı, ölçülülüğü ve liyakati kapsar." },
    { kod: "D1.1", ad: "Hak ve özgürlüklerini bilmek ve korumak" },
    { kod: "D1.2", ad: "Hakkaniyetli davranmak" },
    { kod: "D1.3", ad: "Ölçülü ve dengeli olmak" },
    { kod: "D1.4", ad: "Liyakate önem vermek" },
    { kod: "D2", ad: "Aile Bütünlüğü", tanim: "Aile içi iletişim ve iş birliğini güçlendirmeyi, ailede sorumlulukları yerine getirmeyi, aileyle vakit geçirmeyi; saygı, sevgi ve güvene dayalı ilişkiler kurmayı kapsar." },
    { kod: "D2.1", ad: "Aile birliğine önem vermek" },
    { kod: "D2.2", ad: "Aile içi dayanışma göstermek" },
    { kod: "D2.3", ad: "Aile içi iletişimi güçlendirmek" },
    { kod: "D2.4", ad: "Aile içi sorumlulukları yerine getirmek" },
    { kod: "D3", ad: "Çalışkanlık", tanim: "Disiplinli, planlı ve istikrarlı olmayı; bilimselliğe önem vermeyi, iç motivasyon ve öz denetim sahibi olmayı, hayat boyu öğrenmeyi, görev ve sorumluluk üstlenmeyi kapsar." },
    { kod: "D3.1", ad: "Azimli olmak" },
    { kod: "D3.2", ad: "Planlı olmak" },
    { kod: "D3.3", ad: "Araştırmacı ve sorgulayıcı olmak" },
    { kod: "D3.4", ad: "Çalışmalarda aktif rol almak" },
    { kod: "D4", ad: "Dostluk", tanim: "Sosyal ilişkilerde duyarlılık göstermeyi dayanışma içinde olmayı; etkili iletişimle sevgi, saygı ve güvene dayalı ilişkiler kurmayı; nitelikli vakit geçirmeyi ve evrensel bağ kurmayı kapsar." },
    { kod: "D4.1", ad: "Arkadaşlarına destek olmak" },
    { kod: "D4.2", ad: "Arkadaşları ile etkili iletişim kurmak" },
    { kod: "D4.3", ad: "Güvene dayalı ilişkiler kurmak" },
    { kod: "D4.4", ad: "Arkadaşlarını ve onlarla vakit geçirmeyi önemsemek" },
    { kod: "D4.5", ad: "Farklı kültürlerle bağ kurmak" },
    { kod: "D5", ad: "Duyarlılık", tanim: "Kendisine, içinde yaşadığı topluma, kültürel zenginliklere, tüm varlıklara değer vermeyi; sürdürülebilirliği önemsemeyi ve afetlere karşı hazırlıklı olmayı kapsar." },
    { kod: "D5.1", ad: "İnsana ve topluma değer vermek" },
    { kod: "D5.2", ad: "Çevreye ve canlılara değer vermek" },
    { kod: "D5.3", ad: "Afet bilincine sahip olmak" },
    { kod: "D6", ad: "Dürüstlük", tanim: "Söz ve davranışlarında tutarlı, doğru ve güvenilir olmayı kapsar." },
    { kod: "D6.1", ad: "Samimi olmak" },
    { kod: "D6.2", ad: "Doğru ve güvenilir olmak" },
    { kod: "D7", ad: "Estetik", tanim: "Sanatsal bakış açısı kazanmayı, sanatsal ve kültürel varlığı koruyup zenginleştirmeyi, doğal güzelliklerin ve çevrenin korunması ile ilgili duyarlı olmayı ve sorumluluk üstlenmeyi, estetik aracılığıyla özgün üretkenliği ve ruhsal gelişimi desteklemeyi, sanatı hayatın bir parçası hâline getirmeyi kapsar." },
    { kod: "D7.1", ad: "Duyusal derinliği anlamak" },
    { kod: "D7.2", ad: "Üretkenliği ve ruhsal gelişimi desteklemek" },
    { kod: "D7.3", ad: "Sanatsal ve görsel zevkleri hayatın bir parçası hâline getirmek" },
    { kod: "D8", ad: "Mahremiyet", tanim: "Kendisinin, ailesinin ve başkalarının kişisel alanını ve bilgilerini korumayı; başkalarının özgürlüklerini ihlal etmemeyi, kişisel sınırlarına saygı duymayı ve millî ve manevi değerlerde mahremiyetin sınırlarını kapsar." },
    { kod: "D8.1", ad: "Kişisel özgürlük alanını korumak" },
    { kod: "D8.2", ad: "Kişisel bilgilerin gizliliğini korumak" },
    { kod: "D8.3", ad: "Aile içi ilişkilerde gizliliğe önem vermek" },
    { kod: "D8.4", ad: "Sosyal ilişkilerde kişisel alanları korumak" },
    { kod: "D9", ad: "Merhamet", tanim: "İnsanlara ve diğer canlılara karşı vicdanlı, şefkatli, sevgi dolu, duyarlı ve sorumlu olmayı kapsar." },
    { kod: "D9.1", ad: "Vicdanlı olmak" },
    { kod: "D9.2", ad: "Şefkatli olmak" },
    { kod: "D9.3", ad: "İnsanı ve doğayı sevmek" },
    { kod: "D10", ad: "Mütevazılık", tanim: "Kendini bilmeyi; gösterişten ve kibirden uzak, sade, sabırlı, saygılı, duyarlı ve yapıcı olmayı kapsar." },
    { kod: "D10.1", ad: "Kendini tanımak" },
    { kod: "D10.2", ad: "Gösteriş ve övünmekten kaçınmak" },
    { kod: "D10.3", ad: "İnsan ilişkilerinde yapıcı olmak" },
    { kod: "D11", ad: "Özgürlük", tanim: "Cesur, girişimci ve kararlı olmayı; özgürlüklerini kullanırken kişisel ve toplumsal haklara saygı göstermeyi kapsar." },
    { kod: "D11.1", ad: "Cesaretli ve girişimci olmak" },
    { kod: "D11.2", ad: "Kararlı olmak" },
    { kod: "D11.3", ad: "Kişisel ve toplumsal haklara saygı göstermek" },
    { kod: "D12", ad: "Sabır", tanim: "Olumlu bakış açısına sahip olmayı, zor ve kötü durumlara karşı dayanmayı, istikrarlı davranmayı, süreci yönetmeyi, sorumlulukları yerine getirmeyi; duygu, düşünce ve eylemleri kontrol etmeyi kapsar." },
    { kod: "D12.1", ad: "Olumlu bakış açısına sahip olmak" },
    { kod: "D12.2", ad: "Düşünce, duygu ve davranışlarında kontrollü olmak" },
    { kod: "D12.3", ad: "İstikrarlı olmak" },
    { kod: "D13", ad: "Sağlıklı Yaşam", tanim: "Yeterli, dengeli ve sağlıklı beslenmeyi; sosyal ve sportif etkinliklere katılmayı, bağımlılıktan kaçınmayı, bağımlılıkla mücadele etmeyi ve insan sağlığını önemsemeyi kapsar." },
    { kod: "D13.1", ad: "Yeterli, dengeli ve sağlıklı beslenmek" },
    { kod: "D13.2", ad: "Sosyal ve sportif etkinliklere katılmak" },
    { kod: "D13.3", ad: "Bağımlılıktan kaçınmak ve bağımlılıkla mücadele etmek" },
    { kod: "D13.4", ad: "İnsan sağlığını önemsemek" },
    { kod: "D14", ad: "Saygı", tanim: "Nazik olmayı, ilkeli davranmayı, empati ve etkili iletişim kurmayı, sağlıklı yaşamayı; kendisine, çevresine, millî ve manevi değerlere önem vermeyi kapsar." },
    { kod: "D14.1", ad: "Nezaketli olmak" },
    { kod: "D14.2", ad: "Kendisine saygı duymak" },
    { kod: "D14.3", ad: "Çevresine, millî ve manevi değerlerine saygı duymak" },
    { kod: "D15", ad: "Sevgi", tanim: "Ailesine, dostlarına ve ülkesine karşı vefalı, dürüst, sadık ve özverili olmayı; barışçıl bakış açısına sahip olmayı; misafirperverliği, doğaya ve bütün canlılara karşı merhametli davranmayı kapsar." },
    { kod: "D15.1", ad: "Anlayışlı ve barışçıl olmak" },
    { kod: "D15.2", ad: "Vefalı olmak" },
    { kod: "D15.3", ad: "Sadakatli olmak" },
    { kod: "D15.4", ad: "Özverili olmak" },
    { kod: "D15.5", ad: "Misafirperverlik" },
    { kod: "D16", ad: "Sorumluluk", tanim: "Kendisine ve çevresine karşı görevlerini tam ve zamanında yerine getirmeyi; duygu, düşünce ve eylemlerinin sonucunu kabul etmeyi kapsar." },
    { kod: "D16.1", ad: "Kendine karşı görevlerini yerine getirmek" },
    { kod: "D16.2", ad: "Topluma karşı görevlerini yerine getirmek" },
    { kod: "D16.3", ad: "Görev bilincine sahip olmak" },
    { kod: "D17", ad: "Tasarruf", tanim: "Maddi kaynakları planlı ve kontrollü harcamayı, israftan kaçınmayı, tutumlu olmayı, birikim yapmayı, sahip olduklarının değerini bilmeyi ve bilinçli tüketici olmayı kapsar." },
    { kod: "D17.1", ad: "Bilinçli tüketici olmak" },
    { kod: "D17.2", ad: "İsraftan kaçınmak" },
    { kod: "D17.3", ad: "Sahip olduklarının değerini bilmek" },
    { kod: "D18", ad: "Temizlik", tanim: "Kişisel temizlik ve bakıma dikkat ederek kendisine ve topluma saygı duymayı, yaşadığı ortamın ve çevrenin temizliğine önem vererek toplumdaki genel yaşam kalitesine ve sürdürülebilirliğe katkıda bulunmayı kapsar." },
    { kod: "D18.1", ad: "Kişisel temizlik ve bakımına önem vermek" },
    { kod: "D18.2", ad: "Yaşadığı ortamın temizliğine dikkat etmek" },
    { kod: "D18.3", ad: "Çevresel temizliğe ve sürdürülebilirliğe önem vermek" },
    { kod: "D19", ad: "Vatanseverlik", tanim: "Millî, manevi, insani, kültürel değerleri ve ülke varlıklarını korumayı, sevmeyi ve onlara saygı duymayı; bağımsızlığa önem vermeyi, ülkesi için sorumluluk almayı kapsar." },
    { kod: "D19.1", ad: "Millî bilinç sahibi olmak" },
    { kod: "D19.2", ad: "Millî kimliğini tanımak" },
    { kod: "D19.3", ad: "Ülke varlıklarına sahip çıkmak" },
    { kod: "D19.4", ad: "Bağımsızlığı korumak" },
    { kod: "D20", ad: "Yardımseverlik", tanim: "İnsanlara ve canlılara duyarlı olmayı, onları sevmeyi, onlara merhamet etmeyi, cömertliği, dayanışmayı, fedakârlık yapmayı, iyiliksever olmayı kapsar." },
    { kod: "D20.1", ad: "Cömert olmak" },
    { kod: "D20.2", ad: "Dayanışma ve fedakârlık göstermek" },
    { kod: "D20.3", ad: "İyiliksever olmak" },
    { kod: "D20.4", ad: "Gönüllü olmak" },
  ],
  "Kavramsal Beceriler": [
    { kod: "KB1", ad: "Temel Beceriler", tanim: "Karmaşık bir süreç gerektirmeden edinilen, gözlenebilen eylemleri ifade eder." },
    { kod: "KB1.1", ad: "Sayma" },
    { kod: "KB1.2", ad: "Okuma" },
    { kod: "KB1.3", ad: "Yazma" },
    { kod: "KB1.4", ad: "Çizim Yapma" },
    { kod: "KB1.5", ad: "Bulma" },
    { kod: "KB1.6", ad: "Seçme" },
    { kod: "KB1.7", ad: "Belirleme" },
    { kod: "KB1.8", ad: "İşaret Etme" },
    { kod: "KB1.9", ad: "Ölçme" },
    { kod: "KB1.10", ad: "Sunma" },
    { kod: "KB1.11", ad: "Çevirmek" },
    { kod: "KB1.12", ad: "Kaydetme" },
    { kod: "KB2", ad: "Bütünleşik Beceriler", tanim: "Süreç modellemesi yapılabilen eylemleri ifade eder; yirmi bütünleşik beceri tanımlanmıştır." },
    { kod: "KB2.1", ad: "Çelişki Giderme Becerisi", tanim: "İki veya daha fazla olay/konu/durum arasındaki tutarsızlığı düzeltme çabasını ifade eder." },
    { kod: "KB2.2", ad: "Gözlemleme Becerisi", tanim: "Doğal ortamdaki nesne ve olaylara ait özelliklerin duyular aracılığıyla belirlenmesini ifade eder." },
    { kod: "KB2.3", ad: "Özetleme Becerisi", tanim: "Bir metnin ya da konuşmanın özünü anlamayı, ana hatlarıyla kısaltarak yorumlamayı ve kendi cümleleri ile aktarmayı ifade eder." },
    { kod: "KB2.4", ad: "Çözümleme Becerisi", tanim: "Bir bütünü parçalarına ayırarak parçalar arasındaki ilişkileri belirlemeyi ifade eder." },
    { kod: "KB2.5", ad: "Sınıflandırma Becerisi", tanim: "Nesne, olgu ve olayları, belirlenen özelliklerine ve birbirleriyle ilişkilerine göre gruplara ayırmayı ifade eder." },
    { kod: "KB2.6", ad: "Bilgi Toplama Becerisi", tanim: "Olay/konu/durum ile ilgili istenen bilgiyi çeşitli yöntemlerle elde etmeyi, doğrulamayı ve kaydetmeyi ifade eder." },
    { kod: "KB2.7", ad: "Karşılaştırma Becerisi", tanim: "Birden fazla kavram veya durum arasındaki benzerlik ve farklılıkların belirlenmesini ifade eder." },
    { kod: "KB2.8", ad: "Sorgulama Becerisi", tanim: "Olay/konu/duruma ilişkin farkında olma, anlamlı sorular sorma, bilgi edinme ve bunları değerlendirme sürecini ifade eder." },
    { kod: "KB2.9", ad: "Genelleme Becerisi", tanim: "Çeşitli olay/konu/durumları araştırma ve aralarındaki özellikleri ilişkilendirip genişleterek yargıya varmayı ifade eder." },
    { kod: "KB2.10", ad: "Çıkarım Yapma Becerisi", tanim: "Önerme ve varsayımlara dayalı olarak sonuca ulaşmayı ifade eder." },
    { kod: "KB2.11", ad: "Gözleme Dayalı Tahmin Etme Becerisi", tanim: "Ön gözlemlerden veya deneyimlerden yola çıkarak çıkarım yapmayı ve yargıda bulunmayı ifade eder." },
    { kod: "KB2.12", ad: "Mevcut Bilgiye/Veriye Dayalı Tahmin Etme Becerisi", tanim: "Eldeki veriler üzerinden hesaplamalar yaparak yargıda bulunmayı ifade eder." },
    { kod: "KB2.13", ad: "Yapılandırma Becerisi", tanim: "İlişkileri görme ve bunlardan uyumlu bir bütün oluşturma sürecini ifade eder." },
    { kod: "KB2.14", ad: "Yorumlama Becerisi", tanim: "Mevcut olay/konu/durumu bağlamından koparmadan yeniden açıklamayı ifade eder." },
    { kod: "KB2.15", ad: "Yansıtma Becerisi", tanim: "Deneyimlerden yola çıkarak gözden geçirmeyi, çıkarımda bulunmayı ve değerlendirmeyi ifade eder." },
    { kod: "KB2.16", ad: "Muhakeme (Akıl Yürütme) Becerisi", tanim: "Tümevarım/tümdengelim/analoji yaklaşımlarını kullanarak çıkarımlara ulaşma sürecini ifade eder." },
    { kod: "KB2.17", ad: "Değerlendirme Becerisi", tanim: "Ölçüt belirleyerek ölçme yapmayı ve sonuçları ölçütlerle karşılaştırarak yargıda bulunmayı ifade eder." },
    { kod: "KB2.18", ad: "Tartışma Becerisi", tanim: "Görüşlerini mantıksal çerçevede sunmayı, başka görüşleri dinlemeyi ve kıyaslamayı ifade eder." },
    { kod: "KB2.19", ad: "Mantıksal Denetleme Becerisi", tanim: "Bir önerme ya da çıkarımı akıl ilkelerine uygun şekilde işe koşmayı ifade eder." },
    { kod: "KB2.20", ad: "Sentezleme Becerisi", tanim: "Parçalar arasında ilişki kurarak özgün bir bütün oluşturma sürecini ifade eder." },
    { kod: "KB3", ad: "Üst Düzey Düşünme Becerileri", tanim: "Bütünleşik becerilerden en az ikisini içeren, çok boyutlu zihinsel süreçler gerektiren eylemleri ifade eder; üç üst düzey düşünme becerisi tanımlanmıştır." },
    { kod: "KB3.1", ad: "Karar Verme Becerisi", tanim: "Amacı belirleme, bilgi toplama, seçenekler oluşturma, mantıksal denetleme, seçim yapma ve sonuçlar üzerinde yansıtma yapma becerisini ifade eder." },
    { kod: "KB3.2", ad: "Problem Çözme Becerisi", tanim: "Yapılandırma, özetleme, tahmin etme, akıl yürütme, yansıtma/değerlendirmeyi kapsayan zihinsel işlemleri yürütebilmeyi ifade eder." },
    { kod: "KB3.3", ad: "Eleştirel Düşünme Becerisi", tanim: "Karşılaşılan bilgilere ilişkin sorgulama, akıl yürütme ve yansıtma becerisini ifade eder." },
  ],
  "Eğilimler": [
    { kod: "E1", ad: "Benlik Eğilimleri", tanim: "Kişinin içsel özelliklerini ve kişiliğini, sergileyeceği becerilere yansıtmasını ifade eder; altı benlik eğilimi tanımlanmıştır." },
    { kod: "E1.1", ad: "Merak", tanim: "Yeni ve ilginç bir bilgi veya nesneyle karşılaşıldığında duyulan gözlemleme, araştırma, keşfetme ve anlama arzusunu ifade eder." },
    { kod: "E1.2", ad: "Bağımsızlık", tanim: "Başka kişi, grup ya da otoritenin etkisi olmadan özgür seçimler yapıp bunların sorumluluğunu alabilmeyi ifade eder." },
    { kod: "E1.3", ad: "Azim ve Kararlılık", tanim: "Bir işi yerine getirme konusundaki gayreti ve zorluklara karşı yılmaksızın uygulama çabasını ifade eder." },
    { kod: "E1.4", ad: "Kendine İnanma (Öz Yeterlilik)", tanim: "Hedefleri gerçekleştirme sürecinde gerekli eylemleri planlama ve yürütme becerisine olan kişisel inancı ifade eder." },
    { kod: "E1.5", ad: "Kendine Güvenme (Öz Güven)", tanim: "Bir hedefi gerçekleştirebileceğine ilişkin yeteneğe ve kapasiteye olan inancı ifade eder." },
    { kod: "E1.6", ad: "Seçicilik", tanim: "Anlamlı ve etkili olanı ayırt etme; kendi amaç, değer ve ölçütlerine uygun olanı bilinçli biçimde tercih etmeyi ifade eder." },
    { kod: "E2", ad: "Sosyal Eğilimler", tanim: "Kişinin içsel özelliklerini sosyal bir ortam içinde sergileyeceği becerilere yansıtmasını ifade eder; beş sosyal eğilim tanımlanmıştır." },
    { kod: "E2.1", ad: "Empati", tanim: "Çevresindeki kişilerin duygu ve düşüncelerini hissederek içselleştirip dönüt vermeyi ifade eder." },
    { kod: "E2.2", ad: "Sorumluluk", tanim: "Üstlenilen görevin zamanında yerine getirilmesi ve kararların/eylemlerin sonuçlarını üstlenmeyi ifade eder." },
    { kod: "E2.3", ad: "Girişkenlik", tanim: "Diğer kişilerin haklarına saygılı olmak koşuluyla belirli sınırlar içinde yapılmak istenileni belirleyebilme gücünü ifade eder." },
    { kod: "E2.4", ad: "Güven", tanim: "Karşı tarafın niyet veya davranışlarının ahlaka uygun ve öngörülebilir olma inancını ifade eder." },
    { kod: "E2.5", ad: "Oyunseverlik", tanim: "Öğrenme sürecinin keyifli ve eğlenceli hâle getirilebilmesine ilişkin eğilimi ifade eder." },
    { kod: "E3", ad: "Entelektüel Eğilimler", tanim: "Kişinin zihinsel ve düşünsel birikimlerini sergileyeceği becerilere yansıtmasını ifade eder; on entelektüel eğilim tanımlanmıştır." },
    { kod: "E3.1", ad: "Muhakeme", tanim: "Bilgi, veri ve unsurları dikkatle değerlendirerek mantıklı, tutarlı ve doğru sonuçlara ulaşmayı ifade eder." },
    { kod: "E3.2", ad: "Odaklanma", tanim: "Belirlenen bir hedefe ulaşmak için gereken çabanın en iyi düzeyde kullanılmasını ifade eder." },
    { kod: "E3.3", ad: "Yaratıcılık", tanim: "Alışılagelmiş kalıpların dışında yeni durumlara uyum sağlayarak özgün ürün/fikir üretilmesini ifade eder." },
    { kod: "E3.4", ad: "Gerçeği Arama", tanim: "Gerçeği bulmak için nesnel ve dürüstçe bir yaklaşıma sahip olunmasını, kararlılıkla hareket edilmesini ifade eder." },
    { kod: "E3.5", ad: "Açık Fikirlilik", tanim: "Meraklı, saygılı ve ön yargısız şekilde bakabilmeyi; farklı fikirlere açık olabilmeyi ifade eder." },
    { kod: "E3.6", ad: "Analitiklik", tanim: "Nesnel kanıtlar kullanma ve akıl yürütme yoluyla çözüme ulaşılabilmesini ifade eder." },
    { kod: "E3.7", ad: "Sistematiklik", tanim: "Çeşitli durumların belirli bir yöntemle düzenli ve odaklı şekilde ele alınmasını ifade eder." },
    { kod: "E3.8", ad: "Soru Sorma", tanim: "Bilme ve anlama ihtiyacına yönelik öğrenme ve keşfetme arzusu ile özgürce sorgulamalar yapabilmeyi ifade eder." },
    { kod: "E3.9", ad: "Şüphe Duyma", tanim: "Sunulan bir bilgi karşısında emin olamama durumundan hareketle bilgiyi kontrol ederek ilerlemeyi ifade eder." },
    { kod: "E3.10", ad: "Eleştirel Bakma", tanim: "Bir düşünce, argüman ve bilginin doğruluğunun değerlendirilmesi, güvenilirliğinin tespit edilmesini ifade eder." },
  ],
  "Sosyal-Duygusal Öğrenme Becerileri": [
    { kod: "SDB1", ad: "Benlik Becerileri", tanim: "Kişinin ihtiyacı olan kişisel kaynakları geliştirerek kullanabilmesini ifade eder; üç benlik becerisi tanımlanmıştır." },
    { kod: "SDB1.1", ad: "Kendini Tanıma (Öz Farkındalık Becerisi)", tanim: "Kişisel özelliklerin duygu, düşünce ve davranışlara yansımasının bilincinde olunmasını ifade eder." },
    { kod: "SDB1.2", ad: "Kendini Düzenleme (Öz Düzenleme Becerisi)", tanim: "Kişisel hedeflere ulaşabilmek için duygu, davranış ve bilişsel stratejilerin izlenip kontrol edilmesini ifade eder." },
    { kod: "SDB1.3", ad: "Kendine Uyarlama (Öz Yansıtma Becerisi)", tanim: "Duygu, düşünce ve davranışların dönüştürülüp geliştirilmesi için değerlendirmeler yapılmasını ifade eder." },
    { kod: "SDB2", ad: "Sosyal Yaşam Becerileri", tanim: "Kişinin toplumsal hayata etkin katılabilmek için kullandığı becerileri ifade eder; üç sosyal yaşam becerisi tanımlanmıştır." },
    { kod: "SDB2.1", ad: "İletişim Becerisi", tanim: "Duygu, düşünce veya bilgilerin sözlü ya da sözsüz olarak başkalarına iletilmesini ifade eder." },
    { kod: "SDB2.2", ad: "İş Birliği Becerisi", tanim: "Ortak bir hedefe ulaşmak için iki veya daha fazla kişinin birlikte çalışabilmesini ifade eder." },
    { kod: "SDB2.3", ad: "Sosyal Farkındalık Becerisi", tanim: "Farklı geçmiş, kültür ve şartlardan gelen kişilerin bakış açılarını anlama ve onlarla hemhâl olmayı ifade eder." },
    { kod: "SDB3", ad: "Ortak/Birleşik Beceriler", tanim: "Benlik becerileri ile sosyal yaşam becerilerinin kesişiminde yer alır; üç ortak/birleşik beceri tanımlanmıştır." },
    { kod: "SDB3.1", ad: "Uyum Becerisi", tanim: "Hem benlik hem de çevreyle dengeli bir ilişki kurulup sürdürülebilmesini ifade eder." },
    { kod: "SDB3.2", ad: "Esneklik Becerisi", tanim: "Yeni bir duruma uyum sağlayabilmeyi, mevcut çözümleri güncelleyerek farklı çözümler üretebilmeyi ifade eder." },
    { kod: "SDB3.3", ad: "Sorumlu Karar Verme Becerisi", tanim: "Ahlaki sorumluluk çerçevesinde özenli ve yapıcı seçimler yapılabilmesini ifade eder." },
  ],
  "Okuryazarlık Becerileri": [
    { kod: "OB1", ad: "Bilgi Okuryazarlığı" },
    { kod: "OB1.1", ad: "Bilgi İhtiyacını Fark Etme" },
    { kod: "OB1.2", ad: "Bilgiyi Toplama" },
    { kod: "OB1.3", ad: "Bilgiyi Özetleme" },
    { kod: "OB1.4", ad: "Bilgiyi Sentezleme" },
    { kod: "OB1.5", ad: "Bilgiyi Kullanarak Eleştirel Düşünme" },
    { kod: "OB2", ad: "Dijital Okuryazarlık" },
    { kod: "OB2.1", ad: "Dijital Bilgiye Ulaşma ve Dijital Bilgiyi Tanıma" },
    { kod: "OB2.2", ad: "Dijital İletişimi Anlama" },
    { kod: "OB2.3", ad: "Fikrî Mülkiyet Haklarını Bilerek Davranma" },
    { kod: "OB2.4", ad: "Dijital Bilgiyi Anlamlandırma" },
    { kod: "OB2.5", ad: "Dijital Ortamlar İçin İçerik Oluşturma ve Paylaşma" },
    { kod: "OB2.6", ad: "İletişim Kurma ve Paylaşma" },
    { kod: "OB2.7", ad: "Dijital Araçlarla İş Görme" },
    { kod: "OB2.8", ad: "E-Güvenlik Önlemleri Alma" },
    { kod: "OB2.9", ad: "Dijital Bilgiyi Kullanarak Eleştirel Düşünme" },
    { kod: "OB3", ad: "Finansal Okuryazarlık" },
    { kod: "OB3.1", ad: "Geliri Anlama" },
    { kod: "OB3.2", ad: "Para Yönetimini Sağlama" },
    { kod: "OB3.3", ad: "Bilinçli Harcama Yapma ve Borçlanma" },
    { kod: "OB3.4", ad: "Düzenli Tasarruf Yapma ve Yatırımları Yönetme" },
    { kod: "OB3.5", ad: "Finansal Teknolojileri Anlamlandırma" },
    { kod: "OB4", ad: "Görsel Okuryazarlık" },
    { kod: "OB4.1", ad: "Görseli Anlama" },
    { kod: "OB4.2", ad: "Görseli Yorumlama" },
    { kod: "OB4.3", ad: "Görsel Hakkında Eleştirel Düşünme" },
    { kod: "OB4.4", ad: "Görsel İletişim Uygulamaları Oluşturma" },
    { kod: "OB5", ad: "Kültür Okuryazarlığı" },
    { kod: "OB5.1", ad: "Kültürü Kavrama" },
    { kod: "OB5.2", ad: "Kültürü Sürdürme" },
    { kod: "OB5.3", ad: "Kültürel Etkileşim" },
    { kod: "OB6", ad: "Vatandaşlık Okuryazarlığı" },
    { kod: "OB6.1", ad: "Vatandaşlığı Anlama" },
    { kod: "OB6.2", ad: "Vatandaşlık Hak ve Sorumluluklarını Sorgulama" },
    { kod: "OB6.3", ad: "Vatandaşlık Hak ve Sorumluluklarını Kullanma" },
    { kod: "OB6.4", ad: "Hak Arama" },
    { kod: "OB7", ad: "Veri Okuryazarlığı" },
    { kod: "OB7.1", ad: "Sorular Sorma ve Olası Sonuçları Düşünme" },
    { kod: "OB7.2", ad: "Veri Oluşturma" },
    { kod: "OB7.3", ad: "Verileri Sayısallaştırma ve Ölçme" },
    { kod: "OB7.4", ad: "Verileri Düzenleme ve İşleme" },
    { kod: "OB7.5", ad: "Verileri Görselleştirme" },
    { kod: "OB7.6", ad: "Verileri Basitleştirme ve Dönüştürme" },
    { kod: "OB7.7", ad: "Örüntüleri Betimleme ve Analiz Etme" },
    { kod: "OB7.8", ad: "Bilgiye Ulaşma İçin Veriyi Yorumlama" },
    { kod: "OB7.9", ad: "Yeni Bilgiyi Kullanma ve Yapılandırma" },
    { kod: "OB8", ad: "Sürdürülebilirlik Okuryazarlığı" },
    { kod: "OB8.1", ad: "Sürdürülebilirliği ve Sürdürülebilir Kalkınmayı Anlama" },
    { kod: "OB8.2", ad: "Sürdürülebilir ve Sürdürülebilir Olmayan Sistemleri Anlama" },
    { kod: "OB8.3", ad: "Sürdürülebilir ve Sürdürülebilir Olmayan Sistemleri Çözümleme" },
    { kod: "OB8.4", ad: "Sürdürülebilir ve Sürdürülebilir Olmayan Sistemleri Yapılandırma" },
    { kod: "OB8.5", ad: "Sürdürülebilir Olmayan Sistemlere Yönelik Problemleri ve Sorunları Tartışma" },
    { kod: "OB8.6", ad: "Sürdürülebilir Sistem Davranışlarını Tahmin Eden Araçları Oluşturma/Seçme/Kullanma" },
    { kod: "OB8.7", ad: "Sistemlerin Sürdürülebilirliğini Etkileyen Problemleri Çözme" },
    { kod: "OB8.8", ad: "Sistemlerin Sürdürülebilirliği İçin Geliştirdiği Çözüm Önerilerini Eyleme Dönüştürmek" },
    { kod: "OB9", ad: "Sanat Okuryazarlığı" },
    { kod: "OB9.1", ad: "Sanat Türlerini ve Tekniklerini Anlama" },
    { kod: "OB9.2", ad: "Sanat Eseri İnceleme" },
    { kod: "OB9.3", ad: "Sanatı Kültürel, Tarihî ve Sosyal Bağlamda Anlama" },
    { kod: "OB9.4", ad: "Sanatsal Pratik Geliştirme" },
  ],
  "Fiziksel Beceriler": [],
}

// Tüm becerileri tek listede döndürür (prompt referansı için).
export function tumBeceriler(): Beceri[] {
  return Object.values(SKILLS).flat()
}

// Belirli bir kategori için becerileri döndürür.
export function getBeceriler(kategori: string): Beceri[] {
  return SKILLS[kategori] ?? []
}
